### PR TITLE
use upstream pdfkit

### PR DESCRIPTION
**Pull request by dotlambda**

### CODE REVIEW

**Comment by PeterNjeim** [comment]
Test your commits before you make a PR, this one causes an error for both the userscript and the command-line tool

**Comment by Xmader** [comment]
The fork exists for a reason.
See diff https://github.com/foliojs/pdfkit/compare/master...LibreScore:pdfkit:master

**Comment by dotlambda** [comment]
Sorry. Would it be possible to publish the fork on NPM? Lockfiles don't store all information required for offline installs in the case of got dependencies.

**Comment by PeterNjeim** [comment]
Don't you need internet to get the files from npm? What do you mean "offline install"?

**Comment by dotlambda** [comment]
> Don't you need internet to get the files from npm? What do you mean "offline install"?

You're right, but usually the files I need to download are checksummed in the lockfile. Sadly for git dependencies some checksums are missing.
Maybe I should have said reproducible installation rather than offline installation.

**Comment by PeterNjeim** [comment]
The lock file includes the git commit hash, that's enough for a reproducible build

**Comment by dotlambda** [comment]
> The lock file includes the git commit hash, that's enough for a reproducible build

Sadly not. Your `package-lock.json` doesn't include pdfkit's `devDependencies`. These are however required to run its build script (which wouldn't be necessary for a package published on NPM). Pdfkit does have a `yarn.lock` I guess but `npm` doesn't respect that for obvious reasons.

**Comment by PeterNjeim** [comment]
Fixed in https://github.com/LibreScore/pdfkit/commit/b4cb32eb1734a2f73ba2d92743647b1a91c0e2a8

**Comment by dotlambda** [comment]
Thanks! Can you also update the commit hash in dl-librescore's package-lock.json?

**Pull request closed without merging**
