### PR TITLE
generate API `Authorization` token using MD5

### PR DESCRIPTION
**Pull request by TheAfroOfDoom**
# Summary

- fixes https://github.com/LibreScore/dl-librescore/issues/44

I analyzed the Musescore website's obfuscated scripts to figure out where exactly they were generating the `Authorization` token. This was done by CTRL+F-ing for "Authorization" in each script file and backtracking through the obfuscated code.

The relevant script that sends requests that use `Authorization` tokens is https://musescore.com/static/public/build/musescore_es6/202403/2946.369e9b2f1e68546789b8fe2dd1e8ae53.js. CTRL+F in this file for "Authorization" to find the relevant code snippet, and CTRL+F for `substr(0, 4)` to find where the generate the MD5 input message.

It was determined that they're passing a string into the [md5](https://en.wikipedia.org/wiki/MD5) hashing algorithm and taking the first 4 characters of that string.

I believe this method of auth token generation is more robust than the previous method and should replace it outright. I only skimmed the code, but it appeared to essentially scrape the token from the network requests and re-use it, which we couldn't do in Node. This new method is (should be) platform agnostic.

## Example

for the following parameters:

- id: `5737666`
- type: `img`
- index: `1`

The input to MD5 would be `5737666img1` + \<some string\>. Last night the string in their script was "010", this morning it's changed to "et". **Worth noting that the `dl-librescore` still works for me locally even with the wrong extra string code suffix ("010")?**

MD5 then outputs `2a7e7379ceb687d14c9f602af1c7d709`, the first 4 characters are `2a7e`. This is our `Authorization` token.

You can manually verify this at this page: https://musescore.com/user/32588974/scores/5737666

- go to Network tab (`F12` on Firefox)
- filter requests by `XHR` type
- select request `jmuse?id=5737666&index=1&type=img`
- verify the `Authorization` request header is as expected (`2a7e`)

## Reviewers

I only verified that this works through the CLI and these two sheets:

- https://musescore.com/user/32588974/scores/5737666
- https://musescore.com/who2234/living-with-determination

### CODE REVIEW

**Comment by PeterNjeim** [comment]
Thanks for doing this. Indeed figuring out how the authorization token was generated was my plan to getting it working with node, rather than bypassing cloudflare's bot detection. I'll review this shortly and get back to you

**Comment by TheAfroOfDoom** [comment]
id like to note that the code found in their obfuscated scripts exactly matches the code found in npm package [md5](https://www.npmjs.com/package/md5) -- https://github.com/pvorb/node-md5/blob/master/md5.js

even if they end up changing how they generate their Authorization token we should still always be able to eventually reverse-engineer it -- if a guest user can send requests via the website to download images, mp3s, etc, then this tool will also be able to

**Comment by PeterNjeim** [comment]
Thanks a ton for doing this. I want to ask how you get the `010` and `et`. Maybe I can scrape it on a server that bypasses bot detection and let clients fetch it instead of rewriting the cli to bypass bot detection

**Comment by PeterNjeim** [comment]
Lol I'm blind you already shared how

**Comment by PeterNjeim** [comment]
Your work has been credited in the Discord server's `#announcements` channel

**Comment by PeterNjeim** [comment]
@TheAfroOfDoom Will test it tomorrow but just wanted to let you know that I think it's been patched again

**Comment by PeterNjeim** [comment]
@ElectricAlexis That requires the LibreScore App, but was patched months ago, so unfortunately not. If I ever find a solution I'll share it in the Discord server

**Comment by cross-hello** [comment]
@TheAfroOfDoom could you elaborate where to find the string suffix?

**Comment by cross-hello** [comment]
@PeterNjeim Thank you
image

**Comment by PeterNjeim** [comment]
@TheAfroOfDoom looks like this doesn't work anymore for unsigned in users. Will take a look at it tomorrow

**Comment by TheAfroOfDoom** [comment]
> @TheAfroOfDoom looks like this doesn't work anymore for unsigned in users. Will take a look at it tomorrow

ill do some digging and see what i find

**Comment by PeterNjeim** [comment]
@TheAfroOfDoom Seems to be working again, don't know what was happening last night

**Comment by PeterNjeim** [comment]
@TheAfroOfDoom seems to be failing again. When signed out, it will work in a regular browser window, but will fail in an private browser window (still works using the fallback). The command-line tool is failing intermittently due to this issue happening intermittently. See https://github.com/LibreScore/dl-librescore/issues/68

**Comment by PeterNjeim** [comment]
Regular browser window:
image

---

Private browser window (gets wrong authorization token): 
image
Fallback (different token than the regular browser window): 
image

**Comment by PeterNjeim** [comment]
Or maybe it has nothing to do with being a private window and more to do with possibly being an A/B test

**Comment by PeterNjeim** [comment]
Figured out the issue, the A/B test changes the URL of the file with the substring

The regular window's URL: `https://musescore.com/static/public/build/musescore_es6/202406/2946.262ef0dec42b785f013d31230dcbbfbf.js`
The private window's URL: `https://musescore.com/static/public/build/musescore_fonts_es6/202406/2946.12e8e568b377876036508b3885334eef.js`

**Comment by PeterNjeim** [comment]
Solved in: https://github.com/LibreScore/dl-librescore/commit/aa4fc038e09918d6442e84d3eed5181347c12b41

**Pull request merged**
